# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1385e2974ce8c1c05bacd0f53254876a550009cc37704756be7c3717989607cb8e6674f379766a9b28ce8dd4d64822ef4af6b5be31082d26ba7fcab65649ca33

test:
  secret_key_base: 53f8bc0005b71ec53306a0bf287aae964a426c9be75fb56d76dcb9518b807c7c1c5591d41fb10666ce58282f7a24f87042c537044b3a67993abb37f735b8fea5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
